name: Publish to GitHub Packages and Curseforge using Gradle

on:
  create:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish to Github Packages
        run: ./gradlew publishGprPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Curseforge
        run: ./gradlew curseforge
        env:
          CURSEFORGE_API_KEY: $${{ secrets.CURSEFORGE_API_KEY }}